### ISSUE TITLE
undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'

### ISSUE THREAD

**Issue by Gooberpatrol66** [SoundScapeRenderer/ssr#107]
[build.log](https://github.com/SoundScapeRenderer/ssr/files/2147490/build.log)

**Comment by umlaeute** [comment]
provide a bit more context? (OS, distribution, build-system, compiler) and a log-file that is a bit more readable (starting with proper linebreaks).

it seems that you are using some CI, how do you rule out that the CI setup is not broken in the first place?

and you should pass `-pthread` to the linker.

**Comment by umlaeute** [comment]
@mgeier checkout out [AC_PTHREAD](https://www.gnu.org/software/autoconf-archive/ax_pthread.html).
the current "test" makes weird assumptions.

**Comment by Gooberpatrol66** [comment]
I'm trying to make a gentoo ebuild. GCC 6.4.0.
>and you should pass -pthread to the linker.
How?

**Comment by Gooberpatrol66** [comment]
I see now. In the known issues section. 

`./configure LIBS=-lpthread`

Solved.
