### ISSUE TITLE
Artefacts on source labels (GUI) 

### ISSUE THREAD

**Issue by Taita-Yam** [SoundScapeRenderer/ssr#110]
Thanks for the awesome software!

Recently built on macOS 10.13.3 from the July 5 2018 commit :: 97a92a9d38e4c686d38970684cc726c412e59e0d

The labels on the sources show strange artifacts at some zoom levels, but appear fine at others. 

Screenshot here ::
[https://ibb.co/fVK3Me](url)

The 0.4.2 dmg release (July 2014) doesn't show these artifacts on the same machine. Is it a Qt5 config issue perhaps? TIA.

**Comment by JensAhrens** [comment]
Thanks for bringing this to our attention! 

I would think that this a macOS high density display configuration issue (or so...). It seems that you are able to compile the code yourself, right? 

May I ask you to recompile the current code master and try it again? We added a bit of macOS config a few days a go. I've seen similar issues that not apparent anymore when using the latest code.

**Comment by Taita-Yam** [comment]
Hi Jens,

I have recompiled on the same machine this morning ::

`cd ssr
make clean
./cleanse.sh
git pull origin master
export QT_SELECT=5
export PKG_CONFIG_PATH="/usr/local/opt/qt/lib/pkgconfig:$PKG_CONFIG_PATH"
pkg-config --variable=moc_location Qt5Core # Not sure if this is actually required...but it works
pkg-config --variable=host_bins Qt5Core # Not sure if this is actually required...but it works
./configure
make
make install`

Same result...but this time the behaviour is slightly different. The artefacts are present at zoom levels between 57 and 104 (which is where most of the viewing happens to be). Before, it was possible to find occasional zoom levels where the font was perfectly clear, and a zoom 'integer' either side of it was covered in artefacts.

Cheers Simon

**Comment by JensAhrens** [comment]
Sorry, I don't know where this problem is coming from. None of the machines that I have tested (including High Sierra) shows it. I can therefore not investigate it. 

It's interesting that the behavior changed when you used the current master. So, it does seem to relate to high density displays. The only thing that I can offer is look out for the problem and then tackle it when I encounter it.

**Comment by Taita-Yam** [comment]
Thanks Jens. I'll be building SSR on a new MacMini soon (this one is an old 2012 model) so I'll report on the result - fixed or otherwise.

**Comment by JensAhrens** [comment]
I've noticed the same issue on one of our machines. It disappeared when upgrading the Qt installation from version 5.11.1 to 5.11.2.

**Comment by Taita-Yam** [comment]
This is fixed now in the latest version. Nice work!
