### ISSUE TITLE
"ERROR" macro redefined and fails to compile

### ISSUE THREAD

**Issue by chris-hld** [SoundScapeRenderer/ssr#133]
https://github.com/SoundScapeRenderer/ssr/blob/6a67d658fc79f85e9171a868aea6765bf6b13b74/src/ssr_global.h#L89
conflicts with 
`x86_64-w64-mingw32.static.posix/include/wingdi.h:75: note: this is the location of the previous definition
 #define ERROR 0`.
This leads to compile errors that are dependent on the order of including `ssr_global.h` and fails with things like
`/home/chris/git/ssr-chris/src/trackerrazor.cpp:87:19: error: expression cannot be used as a function
     ERROR(e.what());`

We could put ours in a namespace or rename it to something like SSRERROR like so:
https://github.com/chris-hld/ssr/commit/966e523e5f88ad4477e4debb8bb508fce15b30ba

I think renaming ERROR and also WARNING is the easiest and most robust way.

**Comment by mgeier** [comment]
Ideally, we would implement a better and more flexible logging system that doesn't need any macros.

But for now, I think renaming the macros is the way to go. I just think that `SSRERROR` is quite hard to decipher, wouldn't `SSR_ERROR` be better?

Using a namespace wouldn't work, because the preprocessor doesn't know anything about namespaces.

**Comment by chris-hld** [comment]
Ok, sound good! Will start a PR with this (at least for `SSR_ERROR`).

**Comment by mgeier** [comment]
Cool, that would be great!

But it would be nice if you could also rename WARNING and VERBOSE... (basically everything that's defined in `src/ssr_global.h`) while you are at it!

Those names starting with underscores are actually forbidden by the C++ standard (they are reserved for names used by the compiler implementation), but we should at least also prefix `__SSR_...` to avoid clashes.
