### ISSUE TITLE
Attempt to build on MacOS Mojave looks for GML library

### ISSUE THREAD

**Issue by shadowfaxster** [SoundScapeRenderer/ssr#143]
Trying to build from source on MacOS and it fails to find the GML library. Is this an undocumented dependency? What is this dependency? 

<img width="581" alt="image" src="https://user-images.githubusercontent.com/25755318/56620279-aeddb080-6628-11e9-8ef2-f42a7507b7db.png">

**Comment by mgeier** [comment]
I've made some changes recently and I've not yet updated the docs, sorry for that!
The documentation is still at the state of the last official release, version 0.5.0.

GML is a library that's used for 3D positions and rotations, which is part of our ongoing efforts to extend the SSR to 3D.

The missing information in the manual is that you'll have to get the (new) Git submodules of the SSR repository:

    git submodule update --init

After that, it should work!

**Comment by shadowfaxster** [comment]
That fixed it, thank you! I'm still working through the dependency list to find MacOS equivalents, but this specific issue seems to be fixed now.  

Thanks for the quick answer!
