### ISSUE TITLE
Try to build on MacOS and have a problem in help2man

### ISSUE THREAD

**Issue by js00070** [SoundScapeRenderer/ssr#161]
I successfully runned ./configure and succeeded in most build steps, but have a problem in help2man

`help2man: no locale support (Locale::gettext required)`

the complete output information is as follows

```
Making all in man
help2man \
		--no-info \
                --name="manual page for the `test binaural = binaural -o binaural = generic && echo binaural || echo binaural | tr 'a-z' 'A-Z'` renderer" \
                --output=ssr-binaural.1 \
                --locale=C.UTF-8 ../src/ssr-binaural
help2man: no locale support (Locale::gettext required)
`help2man' generates a man page out of `--help' and `--version' output.

Usage: help2man [OPTION]... EXECUTABLE

 -n, --name=STRING       description for the NAME paragraph
 -s, --section=SECTION   section number for manual page (1, 6, 8)
 -m, --manual=TEXT       name of manual (User Commands, ...)
 -S, --source=TEXT       source of program (FSF, Debian, ...)
 -L, --locale=STRING     select locale (default "C")
 -i, --include=FILE      include material from `FILE'
 -I, --opt-include=FILE  include material from `FILE' if it exists
 -o, --output=FILE       send output to `FILE'
 -p, --info-page=TEXT    name of Texinfo manual
 -N, --no-info           suppress pointer to Texinfo manual
 -l, --libtool           exclude the `lt-' from the program name
     --help              print this help, then exit
     --version           print version number, then exit

EXECUTABLE should accept `--help' and `--version' options and produce output on
stdout although alternatives may be specified using:

 -h, --help-option=STRING     help option string
 -v, --version-option=STRING  version option string
 --version-string=STRING      version string
 --no-discard-stderr          include stderr when parsing option output

Report bugs to <bug-help2man@gnu.org>.
make[1]: *** [ssr-binaural.1] Error 255
make: *** [all-recursive] Error 1
```

**Comment by JensAhrens** [comment]
We've never really found a generally applicable way to avoid this error. If I remember correctly, then it occurs after all the executables have been created and the only consequence is that you don't have the documentation locally (you always find it online at [https://ssr.readthedocs.io/](https://ssr.readthedocs.io/).

So, you should now be able to run `data/ssr` or `data/ssr-binaural` or so (of course when you current directory is the parent SSR directory).

**Comment by js00070** [comment]
@JensAhrens  yes, data/ssr can start normally now. Thanks!

**Comment by mgeier** [comment]
@js00070 Do you need `help2man` for something else?
If not, the easiest solution should be to just uninstall `help2man`, then everything should run without problems.

BTW, the SSR manual mentions problems with `help2man`, but it doesn't really talk about solutions:
https://ssr.readthedocs.io/en/0.5.0/operation.html#homebrew-recommended

A bit more information is there:

https://github.com/SoundScapeRenderer/ssr/blob/fd47b5f5648f09b6658d0772017f7d5d01a60a37/.travis.yml#L40-L42

> yes, data/ssr can start normally now.

Just to make sure: You know that you can run `make install` (or probably `sudo make install`) to install the SSR executables?

**Comment by js00070** [comment]
@mgeier Thank you for reminding me. I uninstalled help2man. Now everything is going well.

**Comment by mgeier** [comment]
I just found out that it's actually quite simple to install the missing Perl module:

    cpan Locale::gettext

See also 0e19712f3dacfb1cfc9b8f2948e3008bd009cccf.
