### ISSUE TITLE
Mac OS Big Sur, Jack 1.9.19, dyld Library not loaded

### ISSUE THREAD

**Issue by janhenhan** [SoundScapeRenderer/ssr#272]
Hi all,

I tried a fresh install of SSR 0.5.0 from the released dmg on an Intel Mac with Big Sur and newest Jack 1.9.19 from https://jackaudio.org/downloads/
Jack is running fine on its own. When I try to start SSR I get the following error message:

dyld: Library not loaded: /Library/Frameworks/Jackmp.framework/Versions/A/Jackmp
  Referenced from: /Applications/SoundScapeRenderer-0.5.0/SoundScapeRenderer.app/Contents/MacOS/ssr-brs
  Reason: image not found

Is anyone else running these combinations of versions without issues? 

Thx,
Jan

**Comment by JensAhrens** [comment]
Hi Jan,

The way JACK gets installed has changed since we created the bundle. I haven’t found a way to make the bundle work on Bug Sur. 

For know, you’ll need to compile SSR. I will not be able to look at this in the very near future. Sorry! 

Best,
Jens

**Comment by JensAhrens** [comment]
BTW, if you're experiencing trouble when compiling SSR, it might be worth installing JACK through Homebrew. That worked for me. (I haven't tested anything else.)

**Comment by janhenhan** [comment]
Thank you, Jens. And I see the same error message had been discussed in the M1 thread (https://github.com/SoundScapeRenderer/ssr/issues/254#issue-877458944).

**Comment by JensAhrens** [comment]
Now that I'm thinking about it, I remember that I did succeed in the summer to create a bundle with the new code. Find it here: https://www.dropbox.com/s/a2qr498b2cyzl23/SoundScapeRenderer-0.5.0-193-ga9373a3.dmg?dl=0 

The caveat is that I didn't code sign it. I don't know if you can get this one past Gatekeeper and actually use it. I will able to look into the code signing soon-ish. Please excuse that I can't anticipate when exactly.

**Comment by janhenhan** [comment]
Great, thank you Jens! With the helpful package list in above mentioned thread, I was already able to compile on my Mac without any issues though!
