### ISSUE TITLE
jack/ecasound mismatch

### ISSUE THREAD

**Issue by orbisvicis** [SoundScapeRenderer/ssr#33]
(ecasoundc_sa) Error='read() error', cmd='cs-connect' last_error='' cmd_cnt=6 last_cnt=5.

libecasoundc1 2.9.1-4
libjack-jackd2-0 1.9.10+20140610git97e0e80b~dfsg-1ubuntu1
Ubuntu Utopic, Linux 3.16.0-28-generic i686

Seems more pervasive than what is mentioned in [Conflicting-JACK-and-Ecasound-versions.](https://dev.qu.tu-berlin.de/projects/ssr/wiki/Known_Issues#Conflicting-JACK-and-Ecasound-versions).

**Comment by mgeier** [comment]
This is yet another mysterious bug, similarly mysterious to #3.

Can you please try if it works if you use only Ecasound and JACK (without the SSR)?

You can try the `ecasound` or `ecaplay` programs, they should automatically use JACK if `jackd` is running.

**Comment by orbisvicis** [comment]
Looks like this was my fault. The ubuntu package dependencies are incorrect, only installing libecasoundc1 but not the ecasound program/server itself.

Once I installed ecasound the program ran perfectly (inside gdb though).

**Comment by umlaeute** [comment]
the deps are more-or-less correct: if you don't want `ssr` to play back sounds (e.g. you just do *live* sources), then there is no need to install `ecasound`.

however, i'll update the deps to at least *recommend* the ecasound package (so it will get installed by default, but can be (left) uninstalled if needed).

**Comment by mgeier** [comment]
Thanks @orbisvicis for clearing this up. I think it wasn't your fault, I guess it was ecasound's fault because they show a very unhelpful error message.
Thanks @umlaeute for fixing the Debian package, this will avoid the problem for most (or even all) future installations!

**Comment by umlaeute** [comment]
i've now prepared the Debian package.

unfortunately Debian is currently in "frozen" state awaiting the next release. Until the release has happened (which might take some time), I will most likely *not* upload the package to Debian/unstable.
