### ISSUE TITLE
TCP/IP remote automation

### ISSUE THREAD

**Issue by ChrisClock** [SoundScapeRenderer/ssr#35]
I am currently writing a Max for live remote control for SSR which uses the TCP/IP client of SSR. I am trying to simultaneously update up to 34 sources at once and I am experiences some difficulties.

1. Does SSR expect one large <request></request> with all updates per time instance or is it fine to send out multiple full requests, one for each source?
2. How often can I send a request? Right now I am trying to update all source positions every 50 ms.

I can currently automate source movement using binaural synthesis without glitches but only for a low number of sources. Using the WFS renderer, automating only one source already spikes the CPU and gives audible glitches.  Interestingly, this only happens when automating, not when updating per mouse (from Ableton Live).

**Comment by mgeier** [comment]
ad 1: both should be OK, but I don't really know if there is a size limit, this isn't really tested.
But 34 sources aren't that many, so it shouldn't be a problem to send all updates at once.

ad 2: I don't really know, IIRC the network interface checks every 10 ms or so ...
If necessary, we could change this ...

Did you consider using the SSR as library in a Max external?

Did you try to compile the SSR externals for Max?
https://github.com/SoundScapeRenderer/ssr/tree/master/flext
The renderers (including the WFS renderer) work very well in Puredata/Linux (including multi-threading), but AFAIK nobody ever tried to compile it for Max.

If this works, you could avoid the whole communication bottleneck.

I find it strange that you get glitches via remote control but no glitches via mouse movement ...
How can I reproduce those glitches?

**Comment by ChrisClock** [comment]
The goal is essentially to combine position automation and source audio in one session, as well as allowing live position manipulation using (MIDI) controllers.
I will rework my patch a little bit and link them. I assume you have no Ableton Live + Max for Live environment but I can try to reproduce everything in Max?
Will let you know how compiling the externals for Max goes, that might be another elegant solution.

**Comment by mgeier** [comment]
> I assume you have no Ableton Live + Max for Live environment

No, I don't.
It might indeed be hard for me to reproduce this, but probably you can upload a recording of the glitches for me to check if those are known artifacts or if something is actually wrong.

You should write to the mailing list: https://groups.google.com/forum/#!forum/SoundScapeRenderer, probably someone else has Live and Max and can try your patches.
I don't think that many SSR users will read the issues here.

I hope compiling the externals works, I think this would be helpful to quite a few people ...

**Comment by ChrisClock** [comment]
I just updated my README to include Jens's commit to change the EOF character. Could be a decent alternative to the VST for Ableton Live users: https://github.com/ChrisClock/m4l-SSR-Remote

I hope I will find the time to do a short video on it soon.
