### ISSUE TITLE
CI: Update macOS and Xcode versions ... once again

### ISSUE THREAD

**Issue by HaHeho** [SoundScapeRenderer/ssr#380]
https://github.com/HaHeho/ssr/actions/runs/7278435279/job/19832862548 for `macos-11, Xcode_11.7` failed with
```
Error: Your Xcode (11.7 => /Applications/Xcode_11.7.app/Contents/Developer) is too outdated.
Please update to Xcode 13.2.1 (or delete it).
Xcode can be updated from the App Store.
```

Hence, at least that one configuration should be removed. To prevent that we have to update these configurations regularly, maybe we should stick to manually selected macOS versions (currently  `macos-11`, `macos-12`, `macos-13`), but an automatically updated Xcode version, e.g., with https://github.com/marketplace/actions/setup-xcode-version.

Also, Apple Silicon runners may be available now, so a configuration should probably be included?
https://github.com/actions/runner-images/blob/main/images/macos/macos-13-arm64-Readme.md.

**Comment by HaHeho** [comment]
Another issue seems to be with `macos-11, Xcode_13.2.1`, which was interrupted after 6 hours of trying to build many packages from source during the homebrew setup step. Not sure why.
https://github.com/HaHeho/ssr/actions/runs/7278435279/job/19844796502

**Comment by mgeier** [comment]
Thanks for reporting this!

> Hence, at least that one configuration should be removed.

Indeed: #383.

> an automatically updated Xcode version, e.g., with https://github.com/marketplace/actions/setup-xcode-version.

We could try that, but I'm not sure it's worth it.
I don't mind updating the versions from time to time.
But if you think automating it would be better, feel free to make a PR.

> Apple Silicon runners may be available now, so a configuration should probably be included?

I wish, but it seems that it is still limited to paying customers, see https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587.
I didn't try it though ...

> was interrupted after 6 hours of trying to build many packages from source during the homebrew setup step. Not sure why.

Let's hope that was just a temporary glitch.

**Comment by mgeier** [comment]
> Let's hope that was just a temporary glitch.

I don't think it actually was, there's this message in the logs:

```
Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.
```

I guess we should drop `macos-11` completely.

**Comment by HaHeho** [comment]
> > an automatically updated Xcode version, e.g., with https://github.com/marketplace/actions/setup-xcode-version.
> 
> We could try that, but I'm not sure it's worth it. I don't mind updating the versions from time to time. But if you think automating it would be better, feel free to make a PR.

It's fine for now, then. :)

> > Apple Silicon runners may be available now, so a configuration should probably be included?
> 
> I wish, but it seems that it is still limited to paying customers, see [actions/runner-images#8439 (comment)](https://github.com/actions/runner-images/issues/8439#issuecomment-1755601587). I didn't try it though ...

That is unfortunate. We will have to wait then.

> > Let's hope that was just a temporary glitch.
> 
> I don't think it actually was, there's this message in the logs:
> 
> ```
> Warning: You are using macOS 11.
> We (and Apple) do not provide support for this old version.
> It is expected behaviour that some formulae will fail to build in this old version.
> It is expected behaviour that Homebrew will be buggy and slow.
> Do not create any issues about this on Homebrew's GitHub repositories.
> Do not create any issues even if you think this message is unrelated.
> Any opened issues will be immediately closed without response.
> Do not ask for help from Homebrew or its maintainers on social media.
> You may ask for help in Homebrew's discussions but are unlikely to receive a response.
> Try to figure out the problem yourself and submit a fix as a pull request.
> We will review it but may or may not accept it.
> ```
> 
> I guess we should drop `macos-11` altogether.

Ah, I did not see that warning before. But the build failed for me on multiple occasions. Hence, dropping `macos-11` seems like the only reasonable option. It's unfortunate, but fair enough.

**Comment by radeva** [comment]
> Also, Apple Silicon runners may be available now, so a configuration should probably be included?

@HaHeho You can try [FlyCI](https://www.flyci.net/)'s M1 and M2 runners. They are on average 2x faster and 2x cheaper than GitHub's **AND** we have a free tier for OSS projects (see below).

# Install Instructions

1. Install [FlyCI app](https://github.com/apps/flyci-prod) and 
2. Easily replace one line of code and start using FlyCI runners:

```diff
jobs:
 ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
   steps:
   - name: 👀 Checkout repo
     uses: actions/checkout@v4
```
# 500 mins/month Free for Public Repos

Since your repo is public, FlyCI offers 500 mins/month of free M1 runner usage with the `flyci-macos-large-latest-m1` runner for public projects. 

Don't hesitate to contact us in case the free tier doesn't suit your needs or you experience any issues with the runners. Our team is here to support you!

Best Regards,
Veselina Radeva
Product Manager at [FlyCI](https://flyci.net/)
