### ISSUE TITLE
MacOSX: Segmentation fault (11) when trying to launch ssr-aap

### ISSUE THREAD

**Issue by dvzrv** [SoundScapeRenderer/ssr#46]
When trying to launch ssr-aap on MacOSX 10.8.5 and JACK, using the packaged version of ssr (4.2) I get a "Segmentation fault: 11" that is kind of hard to trace.
At first I thought it might be related to the configuration file I try to use, but that seems not the case (as afterwards it also happens without).

In between I tried several things, like switching JACK off and on again, not using a configuration file at all, etc.
Once the segmentation fault occurs, it will happen each time, when trying to start ssr-aap.
When not using a configuration file after an initial segfault, I might be able to start ssr after a couple of retries.
Sometimes reinstalling the application helps, but not always.

This is amongst the weirdest bugs I have seen so far, maybe you can make something out of it?
I tried debugging this with a custom bash script, that starts ssr as if using the "renderer selector", nonetheless I can't quite make any sense of this segfault.

Any help would be much appreciated.

**Comment by mgeier** [comment]
Segmentation faults are nasty, but I hope we'll have a chance to find the bug by means of a "traceback". The SSR is by default compiled with debug information, therefore a traceback might help us locate the exact line in the code where the segfault occurs.

I don't know how to get a traceback on OSX, can you try to produce one and post it here?

It might be easier to diagnose if you run the SSR with only one audio thread.

**Comment by mgeier** [comment]
... it might also be called "backtrace" or similar ...

**Comment by dvzrv** [comment]
@mgeier will do, once I get the time to work in the studio again. Most likely next week. Will keep you posted about it!

**Comment by dvzrv** [comment]
@mgeier: could only find dtruss for this and switch the user to an admin.
https://paste.sleepmap.de/view/8782f0fd

**Comment by mgeier** [comment]
Thanks for the additional info. TBH, I don't really understand most of it, and it doesn't show any hints about where in the SSR code the crash happens.

I have no idea if it has anything to do with it, but could you try to run the SSR with only one audio thread?

Could you try to run it without the network interface? Probably this is related to #47?

**Comment by dvzrv** [comment]
Sorry for the long delay. Ran a test last week, but forgot to post here.
The segfault also occurs with the network interface disabled: https://paste.sleepmap.de/view/aba4c1ab
As you can see, I tweaked the dtruss output to feature more detail.

I will post the results of running with only one audio thread later today.

**Comment by dvzrv** [comment]
And here is the dtruss output, when running single-threaded, no network interface: https://paste.sleepmap.de/view/5c21d4a9
I also included the script I used to run this on top of the paste.

**Comment by dvzrv** [comment]
Sorry, I just realized, that the output of the above mentioned pastes are capped.
Please find them attached here:

without network interface:
[20160817161829-ssr_error.txt](https://github.com/SoundScapeRenderer/ssr/files/429923/20160817161829-ssr_error.txt)
single threaded, without network interface:
[20160822124850-ssr_error.txt](https://github.com/SoundScapeRenderer/ssr/files/429922/20160822124850-ssr_error.txt)

For completeness, the script I used to run SSR:
```
#!/usr/bin/env bash

export ECASOUND="/Applications/SoundScapeRenderer-0.4.2/SoundScapeRenderer.app/Contents/MacOS/ecasound"
cd "/Applications/SoundScapeRenderer-0.4.2/SoundScapeRenderer.app/Contents/MacOS/../../.."
dtruss -acfels /Applications/SoundScapeRenderer-0.4.2/SoundScapeRenderer.app/Contents/MacOS/ssr-aap \
  -s /Volumes/Daten/studio-user/.ssr/kleinesstudio.asd \
  -o 5 \
  --threads=1 \
  -I \
  -vvv \
  /Volumes/Daten/studio-user/.ssr/test.xml > /Volumes/Daten/studio-user/.ssr/$(date "+%Y%m%d%H%M%S")-ssr_error.log 2>&1
```

**Comment by mgeier** [comment]
Thanks for the additional info.

I don't know if this is relevant, but you are not supposed to call the executable inside the app bundle like this.
Did you try to start it like [described in the manual](http://ssr.readthedocs.io/en/latest/operation.html#running-via-the-command-line-terminal)?

Alternatively, you can also compile and install the SSR like it's done on Linux, then you can also start it on the terminal like on Linux, which should be much simpler (for someone who knows how to use a terminal).

**Comment by dvzrv** [comment]
Sure thing. Maybe it leads to the SSR being improved.

What do you mean by 
> you are not supposed to call the executable inside the app bundle like this.
though?
The above posted script is very close to the way SSR is started, when selecting the rendering engine from the GUI (apart from the extra flags for the higher order ambisonics, threads, network interface and verbosity).
Directly calling ssr-aap seems also fine, as the ssr script only selects the ssr-app executable when setting the --aap flag.

When freshly installed this all works out fine, but crashes after a second time, once I provided a scene and a setup (but also when selecting the ambisonics rendering engine from the GUI, so there really seems to be no difference).

Without a script like this, there would be no proper way of attaching any form of debugging and logging the output.

**Comment by mgeier** [comment]
It may work if you call the executable that's buried deep within the App Bundle, it's just not the recommended way.

The recommended way is to do it like described in [the documentation](http://ssr.readthedocs.io/en/latest/operation.html#running-via-the-command-line-terminal):

    open -a JackPilot
    open -a SoundScapeRenderer

In the docs linked above, you'll also find how to pass further arguments, e.g.

    open -a SoundScapeRenderer --args --binaural "--config=my_config_file.conf"

Do you get the same errors if you use it like this?

If you find yourself using the command line arguments a lot, it might be easier to compile the SSR like it's done on LInux. This works the same on Mac OS X. The SSR executables will be installed by default to `/usr/local/bin`. If that's in your `$PATH`, you can then start the SSR in the terminal by simply using the executable name, like `ssr-aap`.

Do you get the same errors if you use it like this?

**Comment by dvzrv** [comment]
I will be able to try this on a MacOS Sierra after January 9th.
We'll see if this changes things.

**Comment by JensAhrens** [comment]
We've been seeing a mysterious behavior on Mac OS X lately, which turned out to be related to Ecasound. The symptom was that SSR crashed with a segmentation fault as soon as you opened an audio file or a scene that involved audio files. SSR worked properly for live inputs.

What helped me was the following:

- Download the ecasound source code: http://ecasound.seul.org/download/ecasound-2.9.1.tar.gz
- Compile it (cd into the directory, then `./configure`, then `make`)
- `Make` produces an executable named `ecasound` in the subfolder `ecasound`; use that one to replace the ecasound binary in the SSR app, for example with

```
sudo cp ecasound/ecasound /Applications/SoundScapeRenderer-0.4.XXX/SoundScapeRenderer.app/Contents/MacOS/
```

An (untested) alternative might using Homebrew to re-install ecasound with the command `brew install ecasound --compile-from-source`. Then, replace the binary in the SSR with something like 

```
sudo cp /usr/local/bin/ecasound /Applications/SoundScapeRenderer-0.4.XXX/SoundScapeRenderer.app/Contents/MacOS/
```

 (you can find the location of the installed binary with `which ecasound`)

**Comment by dvzrv** [comment]
I don't have a macOS machine anymore, this bug is very old and likely not relevant anymore.
