### ISSUE TITLE
Centered source in WFS produces no output

### ISSUE THREAD

**Issue by chohner** [SoundScapeRenderer/ssr#48]
Placing a source at exactly [0,0] inside a circular array results in that source not playing at all in WFS mode. Speaker indicators also won't show up.
I suspect no decision as to from where the focused source should be produced can be made?

The same might happen in VBAP but I haven't tested that.

**Comment by mgeier** [comment]
I've noticed that before but I have no clue why this happens. Can you track this down in the code (`src/wfsrenderer.h`)?

**Comment by JensAhrens** [comment]
I would think that the nominal orientation of the focused source is undefined in this case. SSR assumes that the source radiates towards the reference point and selects the active speakers appropriately. This process might fail when the source is located precisely at the reference point.

**Comment by chohner** [comment]
Fixed in https://github.com/SoundScapeRenderer/ssr/pull/49
