### ISSUE TITLE
Remove cleanse.sh

### ISSUE THREAD

**Issue by dennisguse** [SoundScapeRenderer/ssr#64]
cleanse.sh: `# Shell-Script for removing all files that don't belong into the Git repo. `

This can be easily done using `git clean -f -d`.
This command _really_ removes everything that is not part of the GIT.

**Comment by mgeier** [comment]
Probably the comment is misleading, but `cleanse.sh` is supposed to only remove those files that are created by the build system, not just all files that are not managed by Git.

I might have some test files lying around, probably some text files with notes, whatever. I normally don't want to remove those.

Feel free to submit a PR that fixes the aforementioned comment.
