### ISSUE TITLE
ssr-brs: Throwing exceptions from an event handler is not supported in Qt

### ISSUE THREAD

**Issue by Harvie** [SoundScapeRenderer/ssr#69]
ssr-brs 0.4.2 (archlinux) crashes when i try to load audio file

```
Warning: This system does not provide sample buffer support.
I can not enable anti-aliasing for OpenGl stuff. (controller.h:1104)
Warning: Trying to open specified file as audio file. (controller.h:952)

***********************************************************************
* Message from libecasoundc:
* 
* 'ECASOUND' environment variable not set. Using the default value 
* value 'ECASOUND=ecasound'.
***********************************************************************

Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.
```

**Comment by JensAhrens** [comment]
I've seen this on Mac OX. It turned out that Ecasound was the problem, and I needed not only to re-install it but to actually compile it. Here is the corresponding mention in the documentation: http://ssr.readthedocs.io/en/latest/operation.html#ssr-crashes-with-a-segmentation-fault-on-max-os-x It was totally surprising as Ecasound had been working well for a while.

Maybe you're having the same problem. Please keep us updated.

BTW, you can get rid of the libecasoundc message this way: http://ssr.readthedocs.io/en/latest/operation.html#annoying-ecasound-message

**Comment by Harvie** [comment]
@JensAhrens Yeah, that ecasound message might be annoying, however it still does not prevent ssr-brs from working. I think the reason it actually crashes is this:

```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.
```

**Comment by JensAhrens** [comment]
Did you re-install Ecasound? This might fix this problem:
```
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.
```

**Comment by Harvie** [comment]
Well. I reinstalled ecasound package. Nothing changed.
Then i tried to rebuild ecasound package from source package. Still no change.
Am i supposed to fill some bugreport about how archlinux maintainer build the ecasound package?

It's ecasound 2.9.1  (x86_64) With this build script:


```
build() {
  cd "$srcdir/$pkgname-$pkgver"

  # fix ruby 2.0 incompatibility + use vendor_ruby for ruby files
  patch -Np1 -i "$srcdir/ruby2.patch"

  PYTHONPATH=/usr/bin/python2 ./configure \
    --prefix=/usr \
    --with-python-includes=/usr/include/python2.7 \
    --with-python-modules=/usr/lib/python2.7

  make
}

package() {
  cd "$srcdir/$pkgname-$pkgver"

  make DESTDIR="$pkgdir/" install

  # fix for python 2.7
  sed -i 's:bin/env python:bin/env python2:' \
    "$pkgdir/usr/bin/ecamonitor"
}
```

ruby2.patch:

```
ruby2.patch 
diff -aur ecasound-2.9.0.orig/configure ecasound-2.9.0/configure
--- ecasound-2.9.0.orig/configure	2013-03-26 17:14:51.759045636 +0800
+++ ecasound-2.9.0/configure	2013-03-26 17:15:50.502060731 +0800
@@ -6535,7 +6535,7 @@
   rubyecasound_support=no
   ECA_S_RUBY_SITEDIR=""
 else
-  ECA_S_RUBY_SITEDIR="`ruby -e 'require "rbconfig"; include Config; print CONFIG["sitedir"] + "/" + CONFIG["MAJOR"] + "." + CONFIG["MINOR"]'`"
+  ECA_S_RUBY_SITEDIR="`ruby -e 'include RbConfig; print CONFIG["vendordir"] + "/" + CONFIG["MAJOR"] + "." + CONFIG["MINOR"]'`"
 fi
```

I guess there's nothing suspicious...

**Comment by JensAhrens** [comment]
Hmm, funny. You mentioned that the crash happens, when you're loading an audio file (and, presumably, when your loading a scene from an asdf-file that involves loading an audio file). What happens if you load a "live" scene, i.e., when the virtual sources are connected to the sound card inputs?

Copy and paste the following into a text file with extension "asd" and load it in SSR:

```<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="asdf2html.xsl"?>
<asdf
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="asdf.xsd"
	version="0.1">

	<scene_setup>
		<volume>0</volume>
		<source name="Measured" model="point" volume="0">
			<port>1</port>
			<position x="0" y="2"/>
		</source>
	</scene_setup>
</asdf>
```

**Comment by Harvie** [comment]
@JensAhrens That actually works. I had to fiddle a bit with alsamixer, since ssr doesn't seem to allow to set input levels by itself. But in the end i managed to get some sound from mic.

![image](https://cloud.githubusercontent.com/assets/276504/24311318/e658ccfe-10d3-11e7-935c-200c8058aa99.png)

However that's not really solving my use case... I need to process audio files.

In fact i am looking for some way to take mono WAV file and process it through HRTF to get stereo/binaural WAV of that mono sound coming from specified direction (azimuth, elevation and distance). Ideally in manner that would be easily scriptable by bash... Any ideas how should i do this?

**Comment by JensAhrens** [comment]
Great! 
Regarding the input levels: SSR does not interact with the hardware but you can change the gain of individual sound sources. Highlight a source and you will see a small triangle underneath the level meter of the source. Click into the level meter and drag left or right to increase or decrease the gain. Alternatively, you can highlight the source and hit "+" or "-" to increase/decrease the gain in steps of 1 dB. All this is explained in the manual: http://ssr.readthedocs.io/en/latest/gui.html 

Regarding your processing question: You want to do offline processing, right?!? SSR is not made for that. In theory, JACK has a free-wheeling mode, which is essentially offline processing. I remember that we tried this with SSR several years ago and it did not work. I can't remember why. Maybe you want to give it a try and let us know about the result. If that works, then you could specify the source position(s) in an ASD-file (see manual) and call SSR from a script such that SSR records the output (see SSR manual). If you don't want anything realtime, you're probably better off implementing the processing yourself. Matlab, Octave, Python, etc. they all can load audio files, convolve them, and save them.

**Comment by mgeier** [comment]
If you are a Matlab or Octave user, you can also compile the SSR as a MEX file and use it for offline processing. Just have a look at the [mex/](../tree/master/mex) directory.

**Comment by Harvie** [comment]
I am not using matlab or octave, but i've found python script that seems to be doing exactly what i need:
https://github.com/uncopenweb/3DSound
