### ISSUE TITLE
Setting foldmethod for vim in source is unnecessary and too restrictive

### ISSUE THREAD

**Issue by dvzrv** [SoundScapeRenderer/ssr#71]
Every source file has

`
// vim:fdm=expr:foldexpr=getline(v\:lnum)=~'/\\*\\*'&&getline(v\:lnum)!~'\\*\\*/'?'a1'\:getline(v\:lnum)=~'\\*\\*/'&&getline(v\:lnum)!~'/\\*\\*'?'s1'\:'='
`

set, which prevents foldmethod settings (e.g. foldmethod=syntax) of anyone who wants to work with the code, as it sets it to "expr" per default (which - at least for my setup and a plain setup - never folds code at all).
This is too restrictive and [should be removed](https://github.com/SoundScapeRenderer/ssr/pull/70), as it prevents personal workflows and oversight (one has to overwrite foldmethod for every file opened!).

While I agree, that

`
// vim:softtabstop=2:shiftwidth=2:expandtab:textwidth=80:cindent
`

greatly helps in keeping the code clean (at least when a vim user is writing on it), the above does not (and should be set in the users .vimrc, if needed).

**Comment by mgeier** [comment]
Thanks! I guess until now I was the only Vim user handling the code ...

I agree, the foldmethod should not be forced on anyone.

Just out of curiosity, what fold settings are you using?

I think at some point the remaining line could also be removed. Recently, I've used http://editorconfig.org/ a few times and I think it works quite well. It should take care of most of the rules of the current modeline. I don't know about `cindent` though ...
What do you think about that?

Another option would be to use `clang-format` (https://clang.llvm.org/docs/ClangFormat.html), but I've never tried that.

**Comment by dvzrv** [comment]
I try to stick with `foldmethod=syntax`.
This can also be set selectively with `autocmd`.

editorconfig seems like a smart choice! I have not used it so far though (needs to go to README then).
`cindent` seems to be the right choice for this project, however, as we're in the C-style family of languages.
I have no experience with `clang-format` either.

**Comment by dvzrv** [comment]
Merged ([#70](https://github.com/SoundScapeRenderer/ssr/pull/70))!
