### ISSUE TITLE
Build question: IP interface?

### ISSUE THREAD

**Issue by nettings** [SoundScapeRenderer/ssr#76]
Hi *! After updating my git clone, I ran into this error after rerunning ./configure:
configure: error: ip-interface (network (TCP/IP) interface) not available! Use --disable-ip-interface to deactivate.
Following that advice leads to a successful build process, but I hate to miss out on a feature :) So I tried to figure out what was missing, since I couldn't find anything documented. Looking at the configure script, I fould this, which looks bogus to me:
 ```
if test x$enable_ip_interface != xno; then :

    # set have_bla to "yes"
    have_ip_interface=yes

    # run the actual test (if a test was specified)

  CPPFLAGS="$CPPFLAGS -DASIO_STANDALONE"
  ac_fn_cxx_check_header_mongrel "$LINENO" "asio.hpp" "ac_cv_header_asio_hpp" "$ac_includes_default"
if test "x$ac_cv_header_asio_hpp" = xyes; then :

else
  have_ip_interface=no
fi
```
So apparently something about ASIO is tested here, which I shouldn't have to care about, since I'm on Linux. Can anyone clarify?

**Comment by umlaeute** [comment]
there's more things *ASIO* then you might think.
apart from the steinberg one you probably have in mind, there is also the [ASynchronous I/O library](https://think-async.com/), which is the one being (not) detected here.

On Debian systems, it is packaged as `libasio-dev` (I don't know about your flavour of Linux)

**Comment by mgeier** [comment]
... and although our manual would need some improvements, it *does* mention `libasio-dev`: http://ssr.readthedocs.io/en/latest/operation.html#dependencies

The reason for this "new" dependency is that we got rid of the whole huge Boost dependency because we were only using the networking stuff, which is conveniently available as a separate and much much smaller library which happens to be called ASIO.
If you are interested in the details, that's the PR where this happened: https://github.com/SoundScapeRenderer/ssr/pull/59.

The "ASIO" you are talking about will not happen anytime soon, but for some crude Windows-related plans have a look at https://github.com/SoundScapeRenderer/ssr/wiki/SSR-and-Windows.

**Comment by mgeier** [comment]
BTW @nettings if you want to find some error that happens during `./configure`, it may be less confusing to look at [configure.ac](../blob/master/configure.ac), where the relevant section looks like this:

```
ENABLE_FORCED([ip-interface], [network (TCP/IP) interface],
[
  CPPFLAGS="$CPPFLAGS -DASIO_STANDALONE"
  AC_CHECK_HEADER([asio.hpp], , [have_ip_interface=no])
])
```

Another very helpful source of information is the file `config.log`, which is automatically created during the run of `./configure` and it tells you in more detail what was going wrong. In your case it would probably tell you in many words that `asio.hpp` wasn't found.

All this of course wouldn't have helped explaining what ASIO actually is ...

**Comment by nettings** [comment]
Thanks for the explanation! I was happy to find a pre-packaged asio-devel (I'm on openSUSE Tumbleweed here), and the build went through without problems.
Are you guys at AES Berlin? If so, see you soon!
Sorry for missing the docs, they are indeed very good, just in an unexpected place. Can I suggest to replace the generic and not very useful autotools-INSTALL by this short note?
"
Quick start: ./configure && make && sudo make install.
./configure --help shows build options.
For dependencies and more detailed building instructions, 
please look at docs/manual/operation.rst (a plain text file).
"

**Comment by mgeier** [comment]
Sadly, I won't be able to be at AES Berlin.

> Can I suggest to replace the generic and not very useful autotools-INSTALL by this short note?

You could try to reanimate #63.
Or you can make a new PR (or multiple PRs) to improve the documentation.

But please note that `INSTALL` *does* contain very useful information. Did you actually read it?

**Comment by nettings** [comment]
Yeah, it's a bit like the "safety features onboard this aircraft". It's cool for a first-time user of autotools, but it's just as bloated as the rest of the toolkit, and you stop reading it after a while :-D 
I'll try and create a PR with the relevant info prepended to the boilerplate stuff. Still getting my feet wet with git and github, might take a while...
