### ISSUE TITLE
full Qt5 support

### ISSUE THREAD

**Issue by umlaeute** [SoundScapeRenderer/ssr#84]
Qt4 is dead, and even Debian considers removing it (see [Debian#875188](https://bugs.debian.org/875188).

@mgeier told me that there's an experimental Qt5 branch (we i cannot seem to find now).

i'd like the Debian package to support Qt5 asap, therefore I'm asking @JensAhrens for a new release :-)

**Comment by mgeier** [comment]
Sorry I wasn't accurate: it's not a branch in this repos, it's a PR from @chohner: #58.

And there seems to be a problem with retina macbooks: https://github.com/SoundScapeRenderer/ssr/pull/58#issuecomment-288188325

And yes, a new release would be great!

**Comment by JensAhrens** [comment]
The issue in @chohner: #58 that arises on retina displays seems to related to the OpenGL part of the GUI. I've started replacing all OpenGL with Qt5 widgets. It's fairly straightforward. I just had to pause my activities half way as I'm tied into other commitments right now. 

I'll revisit this soon to finish it.
