### ISSUE TITLE
configure.ac needs -D_REENTRANT

### ISSUE THREAD

**Issue by dvzrv** [SoundScapeRenderer/ssr#91]
On Arch Linux, when building from git source, I get plenty of

```
./../apf/apf/cxx_thread_policy.h:31:2: error: #error You need to compile with _REENTRANT defined since this uses threads!                                                 
 #error You need to compile with _REENTRANT defined since this uses threads! 
```

which lets the bulid fail.
`-D_REENTRANT` needs to be added to CPPFLAGS in configure.ac.

**Comment by mgeier** [comment]
Thanks for the report!

It's actually better to remove the check, see #92.
