### ISSUE TITLE
configure.ac needs -lpthread

### ISSUE THREAD

**Issue by dvzrv** [SoundScapeRenderer/ssr#95]
I [build and run the SSR from HEAD](https://aur.archlinux.org/packages/ssr-git/) every once in a while.
Recently, I was cleaning up some of my [build scripts](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ssr-git#n33) and thought `LIBS="${LIBS} -lptrhead"` is now obsolete, but it definitely leads to linker errors (see last comments on that AUR page).

I remember running into that issue during my thesis, but just forgot to report this as a bug!

**Comment by dvzrv** [comment]
Hmm, now that makes me wonder: Shouldn't [configure.ac](https://github.com/SoundScapeRenderer/ssr/blob/master/configure.ac#L253) already take care of this (for gcc)?

**Comment by mgeier** [comment]
It adds `-pthread` for GCC, but only if the user didn't specify `CXXFLAGS`.

Shall we change this to unconditionally append `-pthread`?

Your build script doesn't mention `CXXFLAGS`, but probably that's somehow defined automatically?

**Comment by dvzrv** [comment]
Yes, that'll be the problem, as makepkg (the Arch build system) currently uses `CXXFLAGS="-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt"`
 as defaults.

So adding `-pthread` unconditionally would be the way to go, I guess.

**Comment by JensAhrens** [comment]
Fixed in #92.

**Comment by mgeier** [comment]
AFAICT, this has not yet been fixed.
