### ISSUE TITLE
travis-ci for gcc and clang

### ISSUE THREAD

**Issue by dvzrv** [SoundScapeRenderer/ssr#96]
I'm currently working on a [travis-ci configuration](https://github.com/dvzrv/ssr/tree/travis-integration) (pull request in a bit!).
I'm trying to integrate builds for gcc and clang, but the clang build fails during `./configure`, [trying to make use of asio.hpp](https://github.com/SoundScapeRenderer/ssr/blob/ddc5e5e903e7793cfd0f2172878eeb3fdb54c2bf/configure.ac#L528) (the gcc build doesn't!): [log.txt](https://github.com/SoundScapeRenderer/ssr/files/1817248/log.txt)

I'm a little puzzled as to why this is happening. I can not reproduce this on my machine (clang 5.0.1)!

**Comment by mgeier** [comment]
Is it possible to show the content of `config.log` after the error happens?

**Comment by dvzrv** [comment]
I'll try and cat that to the build!

**Comment by dvzrv** [comment]
Here it is: 
[log-with-config-log.txt](https://github.com/SoundScapeRenderer/ssr/files/1817415/log-with-config-log.txt)

**Comment by mgeier** [comment]
I've come across this annoying `Locale::gettext` thing, but I guess just not installing `help2man` should work, right?

The ASIO error is strange:

```
In file included from /usr/include/asio.hpp:27:
In file included from /usr/include/asio/basic_socket_iostream.hpp:24:
/usr/include/asio/basic_socket_streambuf.hpp:97:21: error: use of undeclared identifier 'steady_timer'
    typename Time = steady_timer::clock_type,
                    ^
```

But `steady_timer` should be defined by ASIO itself ...
There are a lot of preprocessor switches around its definition, probably some of the preprocessor macros are defined differently on `clang`?

**Comment by chris-hld** [comment]
> checking asio.hpp usability... no
checking asio.hpp presence... yes
configure: WARNING: asio.hpp: present but cannot be compiled
configure: WARNING: asio.hpp:     check for missing prerequisite headers?
configure: WARNING: asio.hpp: see the Autoconf documentation
configure: WARNING: asio.hpp:     section "Present But Cannot Be Compiled"
configure: WARNING: asio.hpp: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------- ##
configure: WARNING:     ## Report this to ssr@spatialaudio.net ##
configure: WARNING:     ## ----------------------------------- ##
checking for asio.hpp... no
configure: error: ip-interface (network (TCP/IP) interface) not available! Use --disable-ip-interface to deactivate.

Whats happening here? Is this how it's supposed to be?

**Comment by mgeier** [comment]
@chris-hld The `configure` script looks for the file `asio.hpp`, which it finds, so that's OK.
Then it tries to compile a file called `conftest.cpp` that has basically only this line in it (plus all the preprocessor `#define`s that are available at this point):

    #include <asio.hpp>

However, the compiler fails with the error I mentioned above.
You can see the full source of `conftest.cpp` and the compiler output in the file `config.log`, that's why I asked for it.
The terminal output of `./configure` is not enough to diagnose this.

**Comment by dvzrv** [comment]
@mgeier yes, building without help2man/doxygen is fine, but I wonder, how it is actually used, when others build it on macOS (e.g. #55 ).

Regarding the asio.hpp issue: Yes, `steady_timer::clock_type` should be defined, but [looking at upstream](https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/basic_socket_streambuf.hpp), there have been quite a few changes to the code (I'm still on 1.10.8 here and the integrated version is 1.10.1).
It might be necessary to include a newer version.

In any case, in my version and current upstream in theory this should work (or fail for gcc as well), because of [this](https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/basic_socket_streambuf.hpp#L41). However, in upstream a lot has changed as to [how clock_type is used](https://github.com/chriskohlhoff/asio/blob/master/asio/include/asio/basic_socket_streambuf.hpp#L175).

**Comment by dvzrv** [comment]
Dumping asio 1.12.0 in the build environment seems to make clang happy! :)
Working around a few other issues when selecting several different compiler versions (which would probably be very nice to have).

**Comment by dvzrv** [comment]
@mgeier @JensAhrens please merge #81.
The gcc7 issue now creates the only failure out of nine successful automated builds for Linux and macOS! ;-)
