### ISSUE TITLE
Undefined behavior creating ssr::Connection::Connection()

### ISSUE THREAD

**Issue by chris-hld** [SoundScapeRenderer/ssr#98]
Appears with ASIO 1.10.6 and Windows.
When constructing a new Connection in
https://github.com/SoundScapeRenderer/ssr/blob/989568c62dbde7ce060b23576908d758578af2c8/src/network/connection.cpp#L62
there is a segmentation fault thrown deep inside the ASIO library.
I could trace it back to a mutex lock inside the library.
This smells like undefined behavior / race condition.

A simple, yet very effective fix is adding this 
  `std::this_thread::sleep_for(std::chrono::milliseconds(100));`
just before the constructor.

I wanted to discuss this first, because as far as I know there were no problems with the unix library, correct?
Actually I haven't tested it with the latest (github) release. 
But in my opinion this tiny sleep should avoid any potential race conditions.
100 ms are the timeout intervals in the network interface, too.
Any opinions?

**Comment by mgeier** [comment]
Hmmm, this doesn't really sound like a fix ...

Is this a bug in ASIO? Or in the SSR?

I don't remember any issues on Linux or macOS.

I guess it's unrelated, but we should probably use `std::make_shared()` instead of the raw `new`?

**Comment by chris-hld** [comment]
It's in the interplay of both.
The SSR tries to use Connection while it's still in a (ASIO) mutex lock.
This happens during the constructor. I'm also a bit surprised that adding a sleep BEFORE the constructor helps...

`make_shared<Connection>` won't work because the constructor is private.
However, the typedef `pointer` casts it to a std::shared_ptr<Connection>.

**Comment by chris-hld** [comment]
Ok, I think I have a bit more insight about the lock now:
First, I introduced a longer 3 seconds sleep.
Then, consider this python3 test client

```
import socket
TCP_IP = '127.0.0.1'
TCP_PORT = 4711
BUFFER_SIZE = 1024
MESSAGE = b"<request><reference><orientation azimuth='45'/></reference></request> \n"
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.connect((TCP_IP, TCP_PORT))
s.send(MESSAGE)
for t in range(10):
    data = s.recv(BUFFER_SIZE)
    print ("received data:", data)
s.close()
```

The moment I start the python script I get:
`received data: b'<update><volume>0</volume><transport>stop</transport><reference><position x="0" y="0"/><orientation azimuth="45"/></reference></update>\n'
`

And then, 3 seconds later it starts updating
```
received data: b"<update><reference><orientation azimuth='45'/></reference></update>\n"
received data: b'<update></update>\n'
received data: b'<update></update>\n'
received data: b'<update></update>\n'
received data: b'<update></update>\n'
received data: b'<update></update>\n'
received data: b'<update></update>\n'
received data: b'<update></update>\n'
received data: b'<update></update>\n'
```

So, apparently there already is a connection, even though the pointer is not yet constructed. And it's already in use, to send the first update.
And my guess is that, without the sleep, there is a race condition. Which Windows does not tolerate, UNIX somehow does...

**Comment by mgeier** [comment]
> `make_shared<Connection>` won't work because the constructor is private.

Which constructor?
if `new Connection(...)` works,  `std::make_shared<Connection>(...)` should also work, shouldn't it?

**Comment by chris-hld** [comment]
I'm referring to this private constructor
https://github.com/SoundScapeRenderer/ssr/blob/989568c62dbde7ce060b23576908d758578af2c8/src/network/connection.h#L73

No, `std::make_shared` has no access to private members. Whereas `new` is a (static) class member function and thus does, as far as I understood.

**Comment by mgeier** [comment]
OK, thanks, `std::make_shared<Connection>(...)` indeed doesn't work with a non-public constructor.
But I'm not the only one who finds that surprising:

https://groups.google.com/forum/#!topic/comp.std.c++/b1x0w9eVmRY
https://stackoverflow.com/questions/8147027/how-do-i-call-stdmake-shared-on-a-class-with-only-protected-or-private-const/
https://gist.github.com/RklAlx/6727537
https://rienajouter.blogspot.co.at/2014/10/makeshared-and-makeunique-for-classes.html
http://megalomaniacbore.blogspot.co.at/2016/09/software-engineering-c14-factory-create.html (not portable!)

There seem to be some work-arounds, but I guess the easiest thing is to just leave it as is and to not use `std::make_shared` in this case.

**Comment by chris-hld** [comment]
Discussion moved over to #99.
Fixed.
